using System.CodeDom;
using System.CodeDom.Compiler;
using System.IO;
using UnityEngine;

namespace TanksArmageddon.Core.Editor
{
    public static class FileGenerationTools
    {
        public static void SaveFile(CodeCompileUnit compileUnit, string fileName, bool blankLinesBetweenMembers)
        {
            CodeDomProvider provider = CodeDomProvider.CreateProvider("CSharp");
            string filePath = $"{Application.dataPath}/Source/Scripts/Core/PrefabControl/AutoGenerated/{fileName}.cs";

            using (StreamWriter streamWriter = new(filePath))
            {
                var indentedTextWriter = new IndentedTextWriter(streamWriter);
                var options = new CodeGeneratorOptions
                {
                    BracingStyle = "C",
                    BlankLinesBetweenMembers = blankLinesBetweenMembers
                };

                provider.GenerateCodeFromCompileUnit(compileUnit, indentedTextWriter, options);
                indentedTextWriter.Close();
            }

            Debug.Log($"{fileName} generated successfully");
        }
    }
}
