//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanksArmageddon.Core.PrefabControl
{
    using System.Collections.Generic;
    using UnityEngine;
    
    
    internal class PrefabInfoStorage
    {
        
        private static Dictionary<PrefabName, GameObject> _prefabInstances = new Dictionary<PrefabName, GameObject>();
        
        private static Dictionary<PrefabName, string> _pathsToPrefabs = new Dictionary<PrefabName, string>();
        
        static PrefabInfoStorage()
        {
            _pathsToPrefabs.Add(PrefabName.GameObject1, "Prefabs/GameObject1");
            _pathsToPrefabs.Add(PrefabName.TestObject2, "Prefabs/Test/TestObject2");
        }
        
        public static GameObject GetPrefab(PrefabName prefabName)
        {
            return _prefabInstances[prefabName];
        }
        
        public static void LoadPrefabs()
        {
			foreach (var pathToPrefab in _pathsToPrefabs)
            {
                _prefabInstances[pathToPrefab.Key] = Resources.Load<GameObject>(pathToPrefab.Value);
            }
        }
    }
}
